### ISSUE TITLE
Posted Siemens protocol is out-of-date

### ISSUE THREAD

**Issue by mharms** [nih-fmrif/abcd_protocols#1]
PDF for current Siemens protocol on VE11C is attached.
[ABCD_Prisma_VE11C_protocols__20190320d.pdf](https://github.com/nih-fmrif/abcd_protocols/files/4172820/ABCD_Prisma_VE11C_protocols__20190320d.pdf)

**Comment by Shotgunosine** [comment]
Thanks @mharms! Was this the protocol effective March 2nd, 2019?

**Comment by mharms** [comment]
There isn't really an effective date per se.  Based on its name, it's a protocol that was probably first created around March 20th (not 2nd).  It contains some minor changes to deal with the "SH05" Siemens patch, that different Siemens sites in the study would have installed at different times.

**Comment by Shotgunosine** [comment]
Gotcha, thanks, I'll add it to the repo.
